name: Dependency Update

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Check for dependency updates
        id: updates
        run: |
          ./gradlew dependencyUpdates -Drevision=release --no-daemon > dependency-report.txt
          
          # Extract outdated dependencies
          outdated=$(grep -A 1000 "The following dependencies have later" dependency-report.txt || echo "No updates found")
          echo "UPDATES<<EOF" >> $GITHUB_OUTPUT
          echo "$outdated" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update Gradle Wrapper
        run: |
          ./gradlew wrapper --gradle-version=latest --no-daemon || true

      - name: Create Pull Request
        if: steps.updates.outputs.UPDATES != 'No updates found'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): update dependencies'
          title: 'chore(deps): Automated dependency updates'
          body: |
            ## 🤖 Automated Dependency Update
            
            This PR contains automated dependency updates detected by the dependency checker.
            
            ### Updates Available:
            ```
            ${{ steps.updates.outputs.UPDATES }}
            ```
            
            ### Checklist:
            - [ ] All tests pass
            - [ ] App builds successfully
            - [ ] No breaking changes detected
            - [ ] Release notes reviewed for breaking changes
            
            ### Security Note:
            Please review security advisories for any updated dependencies.
          branch: deps/automated-update
          delete-branch: true
          labels: |
            dependencies
            automated
          reviewers: |
            Anseto1988

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'SnackTrack'
          path: '.'
          format: 'ALL'
          args: >
            --enableRetired
            --enableExperimental
            --failOnCVSS 7

      - name: Upload Security Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: security-audit-report
          path: reports/

      - name: Create Issue for Vulnerabilities
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const title = '🔒 Security Vulnerabilities Detected';
            const body = `## Security Audit Failed
            
            The automated security audit has detected vulnerabilities in the project dependencies.
            
            Please check the [workflow run](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details.
            
            ### Actions Required:
            1. Review the security report in the workflow artifacts
            2. Update vulnerable dependencies
            3. Re-run the security audit
            
            cc @Anseto1988`;
            
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['security', 'high-priority']
            });